version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
sphinx:
  configuration: docs/src/conf.py
python:
  install:
  - method: pip
    path: .
  - requirements: docs/src/requirements.txt
formats:
  - pdf
  - epub
