version: 2

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: true

formats:
-   htmlzip
-   pdf

build:
    os: ubuntu-22.04
    tools:
        python: 3.10

python:
    install:
    -   method: pip
        path: .
        extra_requirements:
        -   docs
