version: 2

sphinx:
    builder: html
    configuration: docs/src/conf.py
    fail_on_warning: true

formats:
-   htmlzip
-   pdf

build:
    image: latest

python:
    version: "3.10"
    install:
    -   method: pip
        path: .
        extra_requirements:
        -   docs
