version: 2

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: true

formats:
-   htmlzip
-   pdf

build:
    os: ubuntu-20.04
    tools:
    -   poetry
    -   python: "3.10"

python:
    install:
    -   method: pip
        path: .
        extra_requirements:
        -   docs
        -   sphinx-autodoc-typehints
